### ISSUE TITLE
Object Storage configuration can't be disabled

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-object-storage#308]
As mentioned in #306, it's not possible to toggle configuration like:

```yaml
micronaut:
  object-storage:
    gcp:
      default:
        enabled: false
    local:
      default:
        enabled: true
        bucket: some-bucket-name
```

This makes the module unusable when having multiple implementations (eg cloud + local) in the classpath.
