### ISSUE TITLE
Breaking change in micronaut-object-storage-gcp:2.0.2 and micronaut-object-storage-local:2.0.2, No bean of type ObjectStorageOperations exists for the given qualifier

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-object-storage#315]
### Expected Behavior

With micronaut-object-storage-gcp:2.0,1 and micronaut-object-storage-local:2.0.1, I could do like in application.yml

```
micronaut:
  object-storage:
    gcp:
      source-storage:
        enabled: true
        bucket: some-production-bucket
```

and this in application-test.yml
```
micronaut:
  object-storage:
    gcp:
      source-storage:
        enabled: false
    local:
      source-storage:
        enabled: true
        bucket: source-storage-test
```

and inject it like this

```
@Named("source-storage") private val sourceStorage: ObjectStorageOperations<*, *, *>
```

### Actual Behaviour

When bumping to  
micronaut-object-storage-gcp:2.0,2 and micronaut-object-storage-local:2.0.2
and starting the app or running tests using `mvn -U clean verify`

```
Message: No bean of type [io.micronaut.objectstorage.ObjectStorageOperations<java.lang.Object,java.lang.Object,java.lang.Object>] exists for the given qualifier: @Named('source-storage'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
```

### Steps To Reproduce

MN:4.0.1
Kotlin 1.9.0

application.yml
```
micronaut:
  object-storage:
    gcp:
      source-storage:
        enabled: true
        bucket: some-production-bucket
```

application-test.yml
```
micronaut:
  object-storage:
    gcp:
      source-storage:
        enabled: false
    local:
      source-storage:
        enabled: true
        bucket: some-test-bucket
```

A `@Singleton` that has `ObjectStorageOperations<*, *, *>` injected
```
@Singleton
class IncomingDocumentStorage(
    @Named("source-storage") private val sourceStorage: ObjectStorageOperations<*, *, *>
) {
    fun saveToSourceBucket(
        someContent: String,
        blobName: String
    ): UploadResponse<*> = sourceStorage.upload(UploadRequest.fromBytes(
        /* bytes = */ someContent.toByteArray(),
        /* key = */ blobName
    ))
}


### Environment Information

_No response_

### Example Application

_No response_

### Version

4.0.1
